[package]
name = "rust-vst"
version = "0.1.0"
edition = "2021"
authors = ["Julien Faro <jfaro@umich.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.3"

[lib]
name = "basicvst"
crate-type = ["cdylib"]